export const ROLES = {
  ADMIN: "ADMINISTRADOR",
  USER: "USUARIO",
};

export const PERMISSIONS = {
  SEARCH_DOCUMENTS: "BUSCAR_DOCUMENTOS",
  VIEW_DOCUMENTS: "VER_DOCUMENTOS",
  DOWNLOAD_DOCUMENTS: "DESCARGAR_DOCUMENTOS",
  UPLOAD_DOCUMENTS: "CARGAR_DOCUMENTOS",
  MANAGE_USERS: "GESTIONAR_USUARIOS",
  MANAGE_PERMISSIONS: "GESTIONAR_PERMISOS",
  VIEW_LOGS: "CONSULTAR_LOGS",
};